tap "homebrew/cask-fonts"
brew "ack"
brew "bash"
brew "coreutils"
brew "git"
brew "gzip"
brew "htop"
brew "imagemagick"
brew "nano"
brew "nmap"
brew "neofetch"
brew "prettyping"
brew "svn"
brew "tldr"
brew "tree"
brew "wget"
brew "wifi-password"
brew "youtube-dl"
cask "alfred"
cask "authy"
cask "adguard"
cask "appcleaner"
cask "bitwarden"
cask "cheatsheet"
cask "discord"
cask "font-comic-neue"
cask "font-fantasque-sans-mono"
cask "font-fira-code"
cask "font-hack"
cask "font-heavy-data-nerd-font"
cask "font-lato"
cask "font-roboto"
cask "font-ubuntumono-nerd-font"
cask "iina"
cask "iterm2"
cask "spotify"
cask "transmission"
cask "transmit"
cask "visual-studio-code"
mas "Amphetamine", id: 937984704
mas "ApolloOne", id: 1044484672
mas "Magnet", id: 441258766
mas "PopClip", id: 445189367
mas "Save to Pocket", id: 1477385213
mas "Spark", id: 1176895641
mas "The Unarchiever", id: 425424353
