tap "homebrew/cask-fonts"
brew "git"
brew "htop"
brew "hugo"
brew "nmap"
brew "prettyping"
brew "python3"
brew "svn"
brew "tldr"
brew "tree"
brew "wget"
cask "alfred"
cask "authy"
cask "adguard"
cask "appcleaner"
cask "cheatsheet"
cask "cryptomator"
cask "font-comic-neue"
cask "font-fantasque-sans-mono"
cask "font-fira-code"
cask "font-hack"
cask "font-heavy-data-nerd-font"
cask "font-lato"
cask "font-roboto"
cask "font-ubuntu-mono-nerd-font"
cask "iina"
cask "istat-menus"
cask "iterm2"
cask "kap"
cask "micro-snitch"
cask "mullvadvpn"
cask "signal"
cask "standard-notes"
cask "tor-browser"
cask "transmission"
cask "transmit"
cask "visual-studio-code"
mas "Amphetamine", id: 937984704
mas "Affinity Designer", id: 824171161
mas "DuckDuckGo", id: 1482920575
mas "Magnet", id: 441258766
mas "PopClip", id: 445189367
mas "Save to Pocket", id: 1477385213
mas "Spark", id: 1176895641
mas "The Unarchiever", id: 425424353
